### ISSUE TITLE
jenkins.sh exec: -v: invalid option

### ISSUE THREAD

**Issue by omrumbakitemiz** [monofor/jenkins-docker#1]
Docker versiyonu: 18.06.1-ce-mac73 (26764)
OS: macOS High Sierra 10.13.6

Projeyi kendi makinemde çalıştırmak istediğimde şu şekilde bir hata alıyorum.

<img width="783" alt="screen shot 2018-09-03 at 14 23 56" src="https://user-images.githubusercontent.com/12871066/44984403-40f35480-af85-11e8-9f97-d9864bfe9d0f.png">

**Comment by se** [comment]
Problemi gördüm şimdi. Sıkıntı command-line'ı yanlış yazmış olmamız. Görmen çok iyi oldu. Düzeltti arkadaş.

Şöyle dener misin?

```sh
docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock monofor/jenkins
```
